version: '3.8'

services:

  portal:
    build: ./portal
    container_name: captive_portal
    ports:
      - "443:443"
    volumes:
      - ${CERT_PATH:-./certs}:/certs:ro
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-change-this-to-a-random-string}
      - SHARED_SECRET=${SHARED_SECRET:-ch4ng3m3}
      - MOCK_PMS_URL=http://mock_pms:5000
      - PMS_TIMEOUT=3
    depends_on:
      - freeradius
      - mock_pms
    restart: unless-stopped

  freeradius:
    build: ./freeradius
    container_name: captive_radius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      - SHARED_SECRET=${SHARED_SECRET:-ch4ng3m3}
      - FORTIGATE_IP=${FORTIGATE_IP:-127.0.0.1}
    restart: unless-stopped

  mock_pms:
    build: ./mock_pms
    container_name: captive_mock_pms
    ports:
      - "5000:5000"
    volumes:
      - pms_data:/data
    environment:
      - DB_PATH=/data/pms.db
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-pms-admin-key}
    restart: unless-stopped

  portal_capport:
    build: ./portal_capport
    container_name: captive_capport
    ports:
      - "8443:8443"
    volumes:
      - ${CERT_PATH:-./certs}:/certs:ro
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-change-this-to-a-random-string}
      - SHARED_SECRET=${SHARED_SECRET:-ch4ng3m3}
      - MOCK_PMS_URL=http://mock_pms:5000
      - MOCK_PMS_ADMIN_URL=http://localhost:5000/admin
      - FGT_HOST=${FGT_HOST:-10.255.112.50}
      - FGT_API_TOKEN=${FGT_API_TOKEN:-}
      - FGT_VDOM=${FGT_VDOM:-root}
      - FGT_VERIFY_TLS=${FGT_VERIFY_TLS:-false}
      - CAPPORT_SERVER_URL=${CAPPORT_SERVER_URL:-https://localhost:8443}
      - FORTIGATE_IP=${FORTIGATE_IP:-127.0.0.1}
      - NAS_IP=${NAS_IP:-127.0.0.1}
      - FGT_RSSO_IP=${FGT_RSSO_IP:-}
      - FGT_RSSO_PORT=${FGT_RSSO_PORT:-1813}
    depends_on:
      - mock_pms
    restart: unless-stopped

volumes:
  pms_data:
